#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM3D v0.9 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2018-2023 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | prepare                                                                    |
# | Prepare OS                                                                 |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

line()
{
  for ((i=0; i<${#SWCR}; i++))
  do
    echo -n "-"
  done
  echo ""
}

SWN1="MM3D"
SWN2="mm3d"
SWCR=`cat documents/copyright`
SWV=`cat documents/VERSION`

echo -e "\n$SWN1 v$SWV prepare OS"
echo "$SWCR"
line
sleep 1
echo "Installing required components..."
sudo apt-get install apache2 \
                     build-essential \
                     git \
                     gnuplot \
                     libswitch-perl \
                     python3-daemon \
                     python3-dev \
                     python3-openssl \
                     python3-requests \
                     python3-rpi.gpio \
                     python3-setuptools \
                     libconfig-tiny-perl \
                     wget
mkdir --parents $HOME/download
cd $HOME/download
git clone https://github.com/adafruit/Adafruit_Python_DHT.git
cd Adafruit_Python_DHT
sudo python3 setup.py install
echo -e "\nSetting Apache2..."
sudo ln --symbolic /etc/apache2/mods-available/cgid.load /etc/apache2/mods-enabled/
sudo ln --symbolic /etc/apache2/mods-available/cgid.conf /etc/apache2/mods-enabled/
sudo ln --symbolic /etc/apache2/conf-available/serve-cgi-bin.conf /etc/apache2/conf-enabled/
sudo /etc/init.d/apache2 restart
echo -e "\nDone."
