#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM3D v0.3 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2018-2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>      |
# | uninstall                                                                  |
# | Uninstaller script                                                         |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

erase()
{
  sudo rm --force $1
  echo "  $1"
}

erasedir()
{
  sudo rmdir $1 2> /dev/null
  echo "  $1"
}

# constans
SWN="MM3D"
SWV=`cat documents/VERSION`
INSTDIR=/usr/local
PRGDIR="mm3d"

# uninstaller
clear
echo "--------------------------------------------------------------------------------"
echo "$SWN $SWV uninstaller script"
echo "Copyright (C) 2018-2019 Pozsar Zsolt <pozsar.zsolt@szerafingomba.hu>"
echo "--------------------------------------------------------------------------------"
sleep 1
echo "Uninstalling..."
echo "- removing files:"
erase "$INSTDIR/bin/$PRGDIR*"
erase "$INSTDIR/etc/$PRGDIR/mm3d.ini"
erase "$INSTDIR/share/doc/$PRGDIR/*"
erase "$INSTDIR/share/$PRGDIR/*"
erase "$INSTDIR/share/man/man1/mm3d*"
erase "$INSTDIR/share/locale/*/mm3d.msg"
erase "/var/local/lib/$PRGDIR/*"
sudo /etc/init.d/mm3d.sh stop
erase "/etc/init.d/$PRGDIR.sh"
erase "/etc/rc0.d/K01mm3d.sh"
erase "/etc/rc2.d/S01mm3d.sh"
erase "/etc/rc3.d/S01mm3d.sh"
erase "/etc/rc4.d/S01mm3d.sh"
erase "/etc/rc5.d/S01mm3d.sh"
erase "/etc/rc6.d/K01mm3d.sh"
sudo systemctl daemon-reload
erase "/usr/lib/cgi-bin/getpage.cgi"
erase "/var/www/html/*.csv"
erase "/var/www/html/*.html"
erase "/var/www/html/pics/*.ico"
erase "/var/www/html/pics/*.png"
erase /etc/cron.d/$PRGDIR
/etc/init.d/cron restart
echo "- removing directories:"
erasedir $INSTDIR/share/doc/$PRGDIR/
erasedir $INSTDIR/share/$PRGDIR/
erasedir $INSTDIR/etc/$PRGDIR/
erasedir /var/local/lib/$PRGDIR/
echo "Done."
