#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM3D v0.7 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2018-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | uninstall                                                                  |
# | Uninstaller script                                                         |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

line()
{
  for ((i=0; i<${#SWCR}; i++))
  do
    echo -n "-"
  done
  echo ""
}

erase()
{
  sudo rm --force $1 2> /dev/null
  echo "  $1"
}

erasedir()
{
  sudo rmdir $1 2> /dev/null
  echo "  $1"
}

# constants
SWN1="MM3D"
SWN2="mm3d"
SWCR=`cat documents/copyright`
SWV=`cat documents/VERSION`
INSTDIR=local

# uninstaller
clear
echo -e "\n$SWN1 v$SWV uninstaller script"
echo "$SWCR"
line
sleep 1
echo "Uninstalling..."
echo "- stopping daemon:"
sudo /etc/init.d/$SWN2.sh stop
sudo systemctl disable mm3d.service
echo "- removing from cron:"
erase "/etc/cron.d/$SWN2"
sudo /etc/init.d/cron restart
echo "- removing files:"
erase "/etc/init.d/$SWN2.sh"
erase "/etc/rc0.d/K01$SWN2.sh"
erase "/etc/rc2.d/S01$SWN2.sh"
erase "/etc/rc3.d/S01$SWN2.sh"
erase "/etc/rc4.d/S01$SWN2.sh"
erase "/etc/rc5.d/S01$SWN2.sh"
erase "/etc/rc6.d/K01$SWN2.sh"
erase "/etc/systemd/system/mm3d.service"
erase "/usr/$INSTDIR/bin/$SWN2*"
erase "/usr/$INSTDIR/share/doc/$SWN2/*"
erase "/usr/$INSTDIR/share/locale/*/$SWN2.msg"
erase "/usr/$INSTDIR/share/man/man1/$SWN2*"
erase "/usr/$INSTDIR/share/man/man7/getenvirconf.cgi.7.gz"
erase "/usr/$INSTDIR/share/man/man7/getdata.cgi.7.gz"
erase "/usr/$INSTDIR/share/man/man7/getpage.cgi.7.gz"
erase "/usr/$INSTDIR/share/man/man8/$SWN2*"
erase "/usr/$INSTDIR/share/$SWN2/*"
erase "/usr/lib/cgi-bin/getdata.cgi"
erase "/usr/lib/cgi-bin/getenvirconf.cgi"
erase "/usr/lib/cgi-bin/getpage.cgi"
erase "/var/$INSTDIR/lib/$SWN2/*"
erase "/var/$INSTDIR/log/$SWN2*"
erase "/var/www/html/*"
erase "/var/www/html/pics/*"
sudo systemctl daemon-reload
echo "- removing directories:"
erasedir "/usr/$INSTDIR/share/doc/$SWN2/"
erasedir "/usr/$INSTDIR/share/$SWN2/"
erasedir "/var/$INSTDIR/lib/$SWN2/"
echo "Done."
