# +----------------------------------------------------------------------------+
# | MM3D v0.6 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2018-2021 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm3d_sk.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=Riadiaci systém MM3D
msg02=Údaje používateľa
msg03=Používateľ
msg04=Názov stránky
msg05=Pestovanie domu
msg06=Mená
msg07=Vstup
msg08=Výstup
msg09=Chyba
msg10=Prejsť na dáta
msg11=Adresa stránky
msg12=Date
msg13=Time
msg14=T
msg15=RH
msg16=Zapnuté
msg17=Vypnuté
msg18=Chyba
msg19=Aktualizované
msg20=Posledný stav
msg21=Dennik
msg22=Kamery
msg23=Ak chcete vidieť celý denník, prihláste sa do jednotky pomocou SSH a použite <i>mm3d-viewlog</i>!
msg24=Prepísať výstupy
msg25=neutrálny
msg26=zapnuté
msg27=vypnutý
msg28=Ak chcete nastaviť prepísanie, prihláste sa do jednotky cez SSH a použite príkaz <i>mm3d-override</i>!
msg29=Ak chcete nastaviť charakteristiku prostredia, prihláste sa do jednotky cez SSH a použite príkaz <i>mm3d-editenvirconf</i>!
