#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM3D v0.7 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2018-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm3d-prepare                                                               |
# | Prepare OS for install MM3D software                                       |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

line()
{
  for ((i=0; i<${#SWCR}; i++))
  do
    echo -n "-"
  done
  echo ""
}

SWN1="MM3D"
SWN2="mm3d"
SWCR="Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>"
SWV="v0.7"

echo -e "\n$SWN1 v$SWV prepare OS"
echo "$SWCR"
line
echo "Installing required components..."
sudo apt-get install build-essential git python-dev
mkdir --parents $HOME/download
cd $HOME/download
git clone https://github.com/adafruit/Adafruit_Python_DHT.git
cd Adafruit_Python_DHT
sudo python setup.py install
echo -e "\nDone."
exit 0
