#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/mm3d-web -a -d /usr/share/doc/mm3d-web ]; then
    ln -sf /usr/share/doc/mm3d-web /usr/doc/mm3d-web
  fi
fi
# End automatically added section
ln --force --symbolic /etc/apache2/mods-available/cgid.load /etc/apache2/mods-enabled/
ln --force --symbolic /etc/apache2/mods-available/cgid.conf /etc/apache2/mods-enabled/
ln --force --symbolic /etc/apache2/conf-available/serve-cgi-bin.conf /etc/apache2/conf-enabled/
invoke-rc.d apache2 restart
mm3d-updatestartpage
