#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM3D v0.6 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2018-2021 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm3d-webpage                                                               |
# | Open webpage with default web browser                                      |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

www-browser localhost
