#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM3D v0.9 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2018-2023 Pozsár Zsolt <pozsarzs@gmail.com>                  |
# | mm3d-override                                                              |
# | Override output status                                                     |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

loadconfiguration()
{
  #CFGFILE="/etc/mm3d/mm3d.ini"
  CFGFILE="/usr/local/etc/mm3d/mm3d.ini"
  if [ ! -f $CFGFILE ]
    then
      echo "ERROR: Cannot open configuration file!"
      exit 1
  fi
  DIR_VAR=`cat $CFGFILE | grep dir_var= | sed 's/dir_var=//'`
}

writetofile()
{
  case $1 in
    "humidifier") OF="out1";;
    "heater") OF="out4";;
    "light") OF="out2";;
    "ventilator") OF="out3";;
    *) usage; exit 2;;
  esac
  if [ $2 = "neutral" ] || [ $2 = "on" ] || [ $2 = "off" ]
  then
    echo -n $2 | sudo tee $DIR_VAR$OF > /dev/null
    echo "Output '"$1"' is set to $2."
    exit 0
  fi
  usage
  exit 2
}

getstatus()
{
  case $1 in
    "humidifier") IF="out1";;
    "heater") IF="out4";;
    "light") IF="out2";;
    "ventilator") IF="out3";;
    *) usage; exit 2;;
  esac
  echo "Port '"$1"' status is:"
  if [ ! -f $DIR_VAR$IF ]
    then
      echo "neutral"
      exit 0
  fi
  cat $DIR_VAR$IF
  echo ""
  exit 0
}

usage()
{
  echo ""
  echo "Usage:"
  echo "    $0 humidifier|light|ventilator|heater neutral|on|off"
  echo ""
}

# main function
loadconfiguration
if [ $# -eq 2 ];
then
  writetofile $1 $2
  exit 0
fi
if [ $# -eq 1 ];
then
  case $1 in
    *) getstatus $1; exit 0;;
  esac
fi
usage
exit 2
