#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM3D v0.5 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2018-2020 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>      |
# | mm3d-editenvirconf                                                         |
# | Edit environment configuration file                                        |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

#CFGFILE="/etc/mm3d/envir.ini"
CFGFILE="/usr/local/etc/mm3d/envir.ini"
if [ ! -f $CFGFILE ]
then
  echo "ERROR: Cannot open configuration file!"
exit 1
fi

sudo mm3d-editenvirconf.bin $CFGFILE
mm3d-stopdaemon
mm3d-startdaemon
exit 0
