#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM3D v0.3 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2018-2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>      |
# | mm3d-editcurrentprog                                                       |
# | Edit current program file                                                  |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

PRGFILE="/home/mm3d/programs/prg_current.py"
if [ ! -e $PRGFILE ]
then
  echo "ERROR: Cannot open current program file!"
exit 1
fi

editor $PRGFILE
exit 0
