#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/mm3d-sw ]; then
  rm -f /usr/doc/mm3d-sw
fi
# End automatically added section
invoke-rc.d mm3d.sh stop

